name: we_chat
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # for using cupertino icons
  cupertino_icons: ^1.0.6

  #for integrating firebase
  firebase_core: ^3.1.1
  # for handling firebase authentication
  firebase_auth: ^5.1.1
  # for handling google sign in
  google_sign_in: ^6.2.1
  # for accessing cloud firestore database
  cloud_firestore: ^5.0.2

  # for showing network image
  cached_network_image: ^3.3.1
  # for picking images
  image_picker: ^1.1.2
  # for accessing firebase storage (for uploading files)
  firebase_storage: ^12.1.0
  # for showing Emojis
  emoji_picker_flutter: ^2.2.0
  # for accessing firebase messaging (push notification)
  firebase_messaging: ^15.0.3
  # for calling restAPIs
  http: ^1.2.2
  # for creating notification channel
  flutter_notification_channel: ^3.1.0
  # for storing images into gallery
  image_gallery_saver: ^2.0.3
  saver_gallery: ^3.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

#flutter_launcher_icons:
#    android: "ic_launcher"
#    ios: true
#    image_path: "images/icon.png"
#    min_sdk_android: 21
#    remove_alpha_ios: true

  # for recommended coding practices
flutter_lints: ^3.0.0


flutter:

 # for enabling material design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
