// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8PfB052BhvJkGxMsLVPuAcLjlH3AWwHA',
    appId: '1:895810718894:android:2b521a8e13bc0268a4713f',
    messagingSenderId: '895810718894',
    projectId: 'we-chat-e944a',
    storageBucket: 'we-chat-e944a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwDsxI2xIslHCE7s3OXwozyt6M4BTQTo',
    appId: '1:895810718894:ios:c1bde97fbc24d8fca4713f',
    messagingSenderId: '895810718894',
    projectId: 'we-chat-e944a',
    storageBucket: 'we-chat-e944a.appspot.com',
    androidClientId: '895810718894-36373neq8quqn8ijf0db2u4jau6j9lqa.apps.googleusercontent.com',
    iosClientId: '895810718894-3tq25tgrmncm4t09729e6qenfdatvfrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

}